### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by cybermakoki** [Alfresco-Business-Reporting/alfresco-business-reporting#2]
Hi, I've just tried to start the server and I'm getting this error:

2015-07-24 11:21:54,515  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webscript.org.alfresco.reportingstatus.get' defined in class path resource [alfresco/module/org.alfresco.reporting/context/reporting-beans-context.xml]: Cannot resolve reference to bean 'alfrescoReportingDatabaseHelper' while setting bean property 'databaseHelperBean'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alfrescoReportingDatabaseHelper' defined in class path resource [alfresco/module/org.alfresco.reporting/context/reporting-beans-context.xml]: Cannot resolve reference to bean 'reportingDAO' while setting bean property 'reportingDAOImpl'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reportingDAO' defined in class path resource [alfresco/module/org.alfresco.reporting/context/mybatis-context.xml]: Cannot resolve reference to bean 'reporting_SqlSessionTemplate' while setting bean property 'reportingTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reporting_SqlSessionTemplate' defined in class path resource [alfresco/module/org.alfresco.reporting/context/mybatis-context.xml]: Cannot resolve reference to bean 'reporting_SqlSessionFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reporting_SqlSessionFactory' defined in class path resource [alfresco/module/org.alfresco.reporting/context/mybatis-context.xml]: Cannot resolve reference to bean 'reportingDialectResourceLoader' while setting bean property 'resourceLoader'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reportingDialectResourceLoader' defined in class path resource [alfresco/module/org.alfresco.reporting/context/mybatis-context.xml]: Cannot resolve reference to bean 'reportingDataSource' while setting bean property 'datasource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reportingDataSource' defined in class path resource [alfresco/module/org.alfresco.reporting/context/mybatis-context.xml]: Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Name [alfrescoReporting] is not bound in this Context. Unable to find [alfrescoReporting].
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1325)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1086)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:580)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
    at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:276)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
    at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

Is the module compatible with postgreSQL?

**Comment by cybermakoki** [comment]
I don't think it's a compatibility problem, I just tried with mysql and having the same errors.

I'm using Alfresco Enterprise 4.2.3.3

**Comment by Martijnvandebrug** [comment]
I added some new actionexecuters, share icons and config. Check out the development branch again, this time it should actually work :)
(tested on Alfresco 4.2.0 and 5.0.1)

**Comment by cybermakoki** [comment]
Hi again, I'm just getting the same error:

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reportingDataSource' defined in class path resource [alfresco/module/org.alfresco.reporting/context/mybatis-context.xml]: Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Name [alfrescoReporting] is not bound in this Context. Unable to find [alfrescoReporting].
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1420)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:322)
    ... 82 more
Caused by: javax.naming.NameNotFoundException: Name [alfrescoReporting] is not bound in this Context. Unable to find [alfrescoReporting].

**Comment by Martijnvandebrug** [comment]
Did you configure Tomcat for JNDI? See the guide at https://code.google.com/p/alfresco-business-reporting/wiki/Home#Installation

**Comment by cybermakoki** [comment]
thanks for that, I forgot to do it.
Now the server starts but I see this in the log, I guess is normal the first time?

 2015-07-27 12:41:47,336  INFO  [reporting.db.DatabaseHelperBean] [localhost-startStop-1]   No reporting tables to display...
 2015-07-27 12:41:47,341  INFO  [alfresco.reporting.ReportingBootstrap] [localhost-startStop-1] Reset all statusses to DONE - starting
 2015-07-27 12:41:47,341  DEBUG [mybatis.impl.ReportingDAOImpl] [localhost-startStop-1] setAllStatusesDoneForTable enter
 2015-07-27 12:41:47,419  FATAL [mybatis.impl.ReportingDAOImpl] [localhost-startStop-1] @@@@ setAllStatusesDoneForTable Exception! : 

### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'alfrescoreporting.lastsuccessfulrun' doesn't exist

### The error may involve defaultParameterMap

### The error occurred while setting parameters

### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'alfrescoreporting.lastsuccessfulrun' doesn't exist

; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'alfrescoreporting.lastsuccessfulrun' doesn't exist
 2015-07-27 12:41:47,538  INFO  [reporting.script.AlfrescoReporting] [localhost-startStop-1] Starting AlfrescoReporting module (Constructor)
 2015-07-27 12:41:47,544  INFO  [reporting.script.AlfrescoReporting] [localhost-startStop-1] Using timezone (for right hour in timestamp): Greenwich Mean Time (+0)

**Comment by Martijnvandebrug** [comment]
Yes it is :)
