### ISSUE TITLE
 Using MySQL as DB, Alfresco Business reporting is not working for Latest community 5.1f.

### ISSUE THREAD

**Issue by shivasakthi18** [Alfresco-Business-Reporting/alfresco-business-reporting#5]
Alfresco Business reporting is not working for community 5.1f.

When can we expect this ? Post your email ID, We would like to develop this, seeking some help to start.

**Comment by tpeelen** [comment]
Thanks for opening this ticket @ GitHub!

Can you explain what fails for you? Does it not start-up? Does it not compile? Does it not harvest? Where should I look at?

Thanks!

-Tjarda

**Comment by shivasakthi18** [comment]
Interesting, we got your reply.

We were not able to compile or build from the lastest code in Git. We tried with the version 1.0.0 amp, and installed into share.war & placed the jar under tomcat/lib. the server is not coming up.. will post the details of the error soon. Meanwhile, any pointers on the link to get the latest amp & jar w.r.t 1.2.0 would be really helpful. and we're trying this with latest community edition of 5.1.f.

**Comment by tpeelen** [comment]
The latest released version is 1.1.0.0, with a 1.2 in beta: https://drive.google.com/open?id=0B99-_8O1gtpHd3VtUE5xQUhNT28

The share lib will not work in tomcat/lib, try tomcat/webapps/share/WEB-INF/lib

Find the documentation at Google Code (still to be migrated) https://code.google.com/archive/p/alfresco-business-reporting/wikis/Home.wiki

Where does the startup of Alfresco crash? Can you post the log? (stack traces and a few lines of correctly booting Alfresco before and after??)

Will check latest build agaist Alfresco CE 5.f soon...

**Comment by shivasakthi18** [comment]
Thank you very much for your prompt response. Let me follow your instruction and post you soon in next 15 - 20 Minutes.

**Comment by shivasakthi18** [comment]
Mean time one error in document MySQL: <Resource defaultTransactionIsolation="-1" -------etc.,
Here auth was specified two times. 

auth="Container" auth="Container"

My friend nvelu will post you more feedback shortly.

**Comment by nvelu-equinix** [comment]
1. Copied the files (org.alfresco.reporting.share.amp & org.alfresco.reporting.amp)
2. executed the apply_amps with -force option.
3. Verified that both of them installed into alfresco.war
4. Edited the context.xml to add the DS for Mysql & added the jndi in web.xml
5. Restarted the service.
6. Below are the errors that we are facing while starting or accessing the /share or /alfrescoo

SEVERE: Error configuring application listener of class org.apache.myfaces.webapp.StartupServletContextListener
java.lang.NoClassDefFoundError: javax/faces/context/ExternalContext
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:116)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4932)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1859)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.faces.context.ExternalContext
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
    ... 18 more

May 01, 2016 5:47:30 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Skipped installing application listeners due to previous error(s)

 2016-05-01 17:47:42,613  INFO  [solr.component.AsyncBuildSuggestComponent] [Suggestor-alfresco-1] Loaded suggester shingleBasedSuggestions, took 751 ms
 2016-05-01 17:48:01,717  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-2] Model tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010000 GetModelsDiff return status is 404
    at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1157)
    at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:249)
    at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:207)
    at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:229)
    at org.alfresco.solr.tracker.CoreWatcherJob.registerForCore(CoreWatcherJob.java:131)
    at org.alfresco.solr.tracker.CoreWatcherJob.execute(CoreWatcherJob.java:74)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:01,820  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-2] Model tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010001 GetModelsDiff return status is 404
    at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1157)
    at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:249)
    at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:207)
    at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:229)
    at org.alfresco.solr.tracker.CoreWatcherJob.registerForCore(CoreWatcherJob.java:131)
    at org.alfresco.solr.tracker.CoreWatcherJob.execute(CoreWatcherJob.java:74)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:15,210  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-6] Model tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010005 GetModelsDiff return status is 404
    at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1157)
    at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:249)
    at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:207)
    at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:229)
    at org.alfresco.solr.component.EnsureModelsComponent.prepare(EnsureModelsComponent.java:80)
    at org.apache.solr.handler.component.AlfrescoSearchHandler.handleRequestBody(AlfrescoSearchHandler.java:283)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
    at org.alfresco.solr.Cloud.getResponse(Cloud.java:159)
    at org.alfresco.solr.Cloud.getSolrDocumentList(Cloud.java:143)
    at org.alfresco.solr.SolrInformationServer.getDocsWithUncleanContent(SolrInformationServer.java:715)
    at org.alfresco.solr.tracker.ContentTracker.doTrack(ContentTracker.java:74)
    at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:185)
    at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:15,249  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-3] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010003 GetModelsDiff return status is 404
    at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1157)
    at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:249)
    at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:207)
    at org.alfresco.solr.tracker.ModelTracker.doTrack(ModelTracker.java:167)
    at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:185)
    at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:15,318  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-7] Model tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010006 GetModelsDiff return status is 404
    at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1157)
    at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:249)
    at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:207)
    at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:229)
    at org.alfresco.solr.component.EnsureModelsComponent.prepare(EnsureModelsComponent.java:80)
    at org.apache.solr.handler.component.AlfrescoSearchHandler.handleRequestBody(AlfrescoSearchHandler.java:283)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
    at org.alfresco.solr.Cloud.getResponse(Cloud.java:159)
    at org.alfresco.solr.Cloud.getSolrDocumentList(Cloud.java:143)
    at org.alfresco.solr.SolrInformationServer.getDocsWithUncleanContent(SolrInformationServer.java:715)
    at org.alfresco.solr.tracker.ContentTracker.doTrack(ContentTracker.java:74)
    at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:185)
    at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:15,332  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-4] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010002 api/solr/aclchangesets return status:404
    at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:162)
    at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:347)
    at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:313)
    at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:104)
    at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:185)
    at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:15,337  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-5] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010004 api/solr/aclchangesets return status:404
    at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:162)
    at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:347)
    at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:313)
    at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:104)
    at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:185)
    at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:30,071  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-13] Model tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010009 GetModelsDiff return status is 404
    at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1157)
    at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:249)
    at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:207)
    at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:229)
    at org.alfresco.solr.component.EnsureModelsComponent.prepare(EnsureModelsComponent.java:80)
    at org.apache.solr.handler.component.AlfrescoSearchHandler.handleRequestBody(AlfrescoSearchHandler.java:283)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
    at org.alfresco.solr.Cloud.getResponse(Cloud.java:159)
    at org.alfresco.solr.Cloud.getSolrDocumentList(Cloud.java:143)
    at org.alfresco.solr.SolrInformationServer.getDocsWithUncleanContent(SolrInformationServer.java:715)
    at org.alfresco.solr.tracker.ContentTracker.doTrack(ContentTracker.java:74)
    at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:185)
    at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:30,121  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-14] Model tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010010 GetModelsDiff return status is 404
    at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1157)
    at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:249)
    at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:207)
    at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:229)
    at org.alfresco.solr.component.EnsureModelsComponent.prepare(EnsureModelsComponent.java:80)
    at org.apache.solr.handler.component.AlfrescoSearchHandler.handleRequestBody(AlfrescoSearchHandler.java:283)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
    at org.alfresco.solr.Cloud.getResponse(Cloud.java:159)
    at org.alfresco.solr.Cloud.getSolrDocumentList(Cloud.java:143)
    at org.alfresco.solr.SolrInformationServer.getDocsWithUncleanContent(SolrInformationServer.java:715)
    at org.alfresco.solr.tracker.ContentTracker.doTrack(ContentTracker.java:74)
    at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:185)
    at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:30,166  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-12] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010007 api/solr/aclchangesets return status:404
    at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:162)
    at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:347)
    at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:313)
    at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:104)
    at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:185)
    at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:30,169  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-11] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010008 api/solr/aclchangesets return status:404
    at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:162)
    at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:347)
    at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:313)
    at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:104)
    at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:185)
    at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-05-01 17:48:30,189  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-17] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04010011 GetModelsDiff return status is 404
    at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1157)
    at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:249)
    at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:207)
    at org.alfresco.solr.tracker.ModelTracker.doTrack(ModelTracker.java:167)
    at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:185)
    at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)

On the side note - We may need to update the google doc instructions for mysql config 1-> auth attribute has been duplicated & driver class name value needs to be updated.

**Comment by shivasakthi18** [comment]
Version of Alfresco we were tried community 5.1f and followed your wiki @ https://code.google.com/archive/p/alfresco-business-reporting/wikis/Home.wiki

**Comment by nvelu-equinix** [comment]
Just an update - followed the instructions @ http://docs.alfresco.com/5.1/tasks/solr-reindex.html to delete all the index. After these steps - tomcat server is not coming up.**
*_Manager console log - *_
Starting Tomcat Server...
Exit code: 1
Stdout:

Stderr:
Unknown error starting tomcat

Couldn't find any other logs under tomcat/logs .. even logs are not getting updated

**Comment by nvelu-equinix** [comment]
Just managed to bring up the tomcat service.. however we are still not able to access /alfresco.

2016-05-02 12:12:18,164  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
 org.alfresco.error.AlfrescoRuntimeException: 04020001 Ensure that the 'dir.root' property 'C:\ALFRES~1\alf_data' is pointing to the correct data location.

##     at org.alfresco.repo.admin.ConfigurationChecker.check(ConfigurationChecker.java:256)

2016-05-02 12:13:00,461  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-1] Model tracking failed

##  org.alfresco.error.AlfrescoRuntimeException: 04020000 GetModelsDiff return status is 404

2016-05-02 12:11:56,679  INFO  [alfresco.repo.admin] [localhost-startStop-1] Using database URL 'jdbc:mysql://localhost/alfresco' with user 'alfresco'.
 2016-05-02 12:11:56,681  INFO  [alfresco.repo.admin] [localhost-startStop-1] Connected to database MySQL version 5.7.12-log
 2016-05-02 12:12:01,700  INFO  [domain.schema.SchemaBootstrap] [localhost-startStop-1] Ignoring script patch (post-Hibernate): patch.db-V4.2-metadata-query-indexes
 2016-05-02 12:12:01,701  INFO  [domain.schema.SchemaBootstrap] [localhost-startStop-1] Ignoring script patch (post-Hibernate): patch.db-V5.1-metadata-query-indexes
 2016-05-02 12:12:11,602  INFO  [reporting.db.DatabaseHelperBean] [localhost-startStop-1] Starting init - MySQL
 2016-05-02 12:12:11,652  INFO  [reporting.db.DatabaseHelperBean] [localhost-startStop-1]   No reporting tables to display...
 2016-05-02 12:12:11,654  INFO  [alfresco.reporting.ReportingBootstrap] [localhost-startStop-1] Reset all statusses to DONE - starting
 2016-05-02 12:12:11,707  FATAL [mybatis.impl.ReportingDAOImpl] [localhost-startStop-1] @@@@ setAllStatusesDoneForTable Exception! : 

### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'alfrescoreporting.lastsuccessfulrun' doesn't exist

### The error may involve defaultParameterMap

### The error occurred while setting parameters

### SQL: UPDATE lastsuccessfulrun   SET status = 'Done'   WHERE status NOT LIKE 'Done'

### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'alfrescoreporting.lastsuccessfulrun' doesn't exist

## ; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'alfrescoreporting.lastsuccessfulrun' doesn't exist

this time the /share url is accessible but not able to login due to issue with /alfresco

**Comment by tpeelen** [comment]
This log statement:
org.alfresco.error.AlfrescoRuntimeException: 04020001 Ensure that the 'dir.root' property 'C:\ALFRES~1\alf_data' is pointing to the correct data location.

indicates that your alf_data folder cannot be found. Please first get your Alfresco up and running without any additional modules (like reporting). If that starts up fine, and is accessible, then we can debug the module(s)...

(My best guess is there is no alfresco.xml or no correctly configured one in tomcat/conf/Catalina/localhost, or the database defined in there does not exist... Just like Alfresco itself, the database needs to exist given the credentials in alfresco.xml)

**Comment by nvelu-equinix** [comment]
thanks.. we have managed to install the amps (individually) by pointing yo MySQL for reporting. We could see the Reporting under DataDictionary.
Moved the report (usersPerSite) to Hourly folder & executing the reporting manually creating the report as pdf under Reopts/MySQL.
Overridden the hourly cron settings to schedule it for every minute just to verify the scheduler.
reporting.execution.frequency.hourly=0 \* \* \* \* ?
however, we could see the follwing error in the log for every min.

2016-05-02 21:56:00,092  ERROR [repo.action.AsynchronousActionExecutionQueueImpl] [defaultAsyncAction7] Failed to execute asynchronous action: Action[ id=dd590b9b-56ed-47c9-9529-82b372899750, node=workspace://SpacesStore/dd590b9b-56ed-47c9-9529-82b372899750 ]: 04020014 
 org.alfresco.service.cmr.replication.ReplicationServiceException: 04020014 
    at org.alfresco.repo.replication.ReplicationActionExecutor.executeImpl(ReplicationActionExecutor.java:266)
    at org.alfresco.repo.action.executer.ActionExecuterAbstractBase.execute(ActionExecuterAbstractBase.java:267)
    at org.alfresco.repo.action.ActionServiceImpl.directActionExecution(ActionServiceImpl.java:839)
    at org.alfresco.repo.action.ActionServiceImpl.executeActionImpl(ActionServiceImpl.java:740)
    at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper$1$1.execute(AsynchronousActionExecutionQueueImpl.java:423)
    at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
    at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:326)
    at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper$1.doWork(AsynchronousActionExecutionQueueImpl.java:432)
    at org.alfresco.repo.tenant.TenantUtil.runAsWork(TenantUtil.java:119)
    at org.alfresco.repo.tenant.TenantUtil.runAsTenant(TenantUtil.java:88)
    at org.alfresco.repo.tenant.TenantUtil$1.doWork(TenantUtil.java:62)
    at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
    at org.alfresco.repo.tenant.TenantUtil.runAsUserTenant(TenantUtil.java:58)
    at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper.run(AsynchronousActionExecutionQueueImpl.java:435)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by shivasakthi18** [comment]
Finally we installed the plugin with MySQL repository on latest stable community version 5.1f where as postgres got some more issue which we will discuss and sort out in another thread...!

Thanks for all your help.
Sivasakthi.
